app/views.py
from flask import Blueprint, render_template,flash, request,redirect,session,url_for
from flask_login import login_required,current_user
from .models import User,Post,Like,Comment,Subscribers
from .requests import find_quote
from .forms import UpdateProfile,PostForm
from . import db, photos
from .email import mail_message, notification_message

views = Blueprint("views",__name__)

@views.route('/',methods = ['POST','GET'])
def home():
   quote = find_quote()
   posts = Post.query.all()
   user = User.query.all()


   if request.method == "POST":
        new_sub = Subscribers(email = request.form.get("subscriber"))
        db.session.add(new_sub)
        db.session.commit()
        mail_message("Thank you for subscribing to the Poetry blog", 
                        "email/welcome", new_sub.email)

   return render_template('index.html',quote = quote,posts=posts,user=user)


#user profile
@views.route('/user/<username>')
def profile(username):
   user = User.query.filter_by(username=username).first()


   if request.method == "POST":
        new_sub = Subscribers(email = request.form.get("subscriber"))
        db.session.add(new_sub)
        db.session.commit()
        mail_message("Thank you for subscribing to the Poetry blog", 
                        "email/welcome", new_sub.email)

   return render_template("profile/profile.html", user = user)

#update profile
@views.route('/user/<username>/update',methods =['GET','POST'])
@login_required
def update_profile(username):
   user = User.query.filter_by(username = username).first()

   form = UpdateProfile()
   if form.validate_on_submit():
        
        username= form.username.data
        user.email = form.email.data
        user.bio = form.bio.data
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('.profile',username=user.username))

   return render_template('profile/update.html',form =form)

#profile pic
@views.route('/user/<username>/update/pic',methods=['POST'])
@login_required
def update_pic(username):
   user = User.query.filter_by(username=username).first()
   if 'photo' in request.files:
      filename = photos.save(request.files['photo'])
      path = f'photos/{filename}'
      user.profile_pic_path = path
      db.session.commit()
   return redirect(url_for('views.profile',username=username))

# write post
@views.route('/post/',methods=['GET','POST'])
@login_required
def post():

   form =PostForm()
   if form.validate_on_submit():
      title= form.title.data
      text =form.text.data
     
      post = Post(title=title,text=text)
      db.session.add(post)
      db.session.commit()
   
      subs = Subscribers.query.all()
      for sub in subs:
            notification_message(title, 
                            "email/notification", sub.email, post = post)
      return redirect(url_for('views.home'))

   return render_template('post.html',user=current_user,form =form)

# comments route
@views.route('/comment/<post_id>',methods=['POST'])
@login_required
def comment(post_id):
   text = request.form.get('text')

   if not text:
      flash('comment cannot be empty',category='error')
   else:
      post = Post.query.filter_by(id=post_id)
      if post:
         comment = Comment(text = text, author=current_user.id, post_id= post_id)
         db.session.add(comment)
         db.session.commit()
      else:
         flash('Post does not exist!',category='error')
       
   return redirect(url_for('views.home'))

# likes route
@views.route('/like/<post_id>',methods=['GET'])
@login_required
def like(post_id):
   post = Post.query.filter_by(id=post_id).first()
   like =Like.query.filter_by(author=current_user.id, post_id = post_id).first()
   
   if not post:
      flash('Post does not exist',category='error')
   elif like:
      db.session.delete(like)
      db.session.commit()
   else:
      like = Like(author=current_user.id, post_id=post_id)
      db.session.add(like)
      db.session.commit()

   return redirect(url_for('views.home'))

app/templates/profile/profile.html
{% extends 'base.html' %}
{% block title %}Profile{% endblock %}

 {% block styles%}
 <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
 {% endblock%}

 {% block content%}
 <div class="container mt-5">
     <div class="row">
         <!-- profile photo -->
          <div class="col-md-4">
             {% if user.profile_pic_path %}
             <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail ppp">
             {%else%}
             <div class="profile-userpic">
                <img src="https://image.ibb.co/jw55Ex/def_face.jpg"
                class="img-responsive" alt="" height="250" width="250">
            </div>
             {% endif %} <br>
             <!-- Update photo -->
             {% if user == current_user %}
             <form id="upload" action="{{url_for('views.update_pic',username=user.username)}}" method="post" enctype = "multipart/form-data">
               <input type="file"  name="photo" class="form-control" required><br>
               <input type="submit">
             </form>
               {% endif %}
         </div>
         <div class="col-md-6">
            <h4>Username: <em>{{user.username}}</em> </h4>
            <!-- bio -->
            {% if user.bio %}
            <h4>Email: <small><em>{{user.email}}</em></small></h4>
            <h4>Bio:  {{user.bio}}</h4>
            {%else%}
                <p> {{user.username}} has no bio </p>
            {% endif %}
            <!-- update -->
            {% if user == current_user %}
            <a href="{{url_for('views.update_profile',username=user.username)}}" class="text-white">Edit profile</a>
            {% endif %}
            <br> <br>
            <em><a href="/post/"class="text-white">Create a post</a></em>

        </div>
     </div> <br><br>
 {% endblock %}
 

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}